### PR TITLE
updating readme

### PR DESCRIPTION
**Pull request by michael-spengler**

### CODE REVIEW

**Comment by cedriking** [comment]
Hello Michael, the method you're showing there is in fact more for a deployed version. To test locally is by doing `npm run dev` instead of `npm run build and npm run start`. Please update to this and I'm able to approve the PR 👍

**Comment by michael-spengler** [comment]
Hi Cedrik. I used npm i && npm run build && npm run start because when i just did npm i && npm run dev the following situation occurred without delivering anything on localhost:1234

Screen Shot 2020-09-24 at 10 03 33

**Comment by cedriking** [comment]
Hey @michael-spengler , this is something that happens because of using parcel with multiple entry points, it's a known bug there but it doesn't cause any issues while working on the project. The only thing is that it requires us to go to `http://localhost:1234/index.html` to be able to see the page instead of just `/`. Because it requires an entry point.

This is also a good thing to add to the docs when editing it 👍 
Thanks Michael.

**Comment by michael-spengler** [comment]
@cedriking Thank you for explaining this --> done 👍

**Pull request merged**
